name: my-expression-action

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "number"
        required: true
        default: "1"
        type: string
      number2:
        description: "number"
        required: true
        default: "1"
        type: string
jobs:
  my-expression-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Output the sum
        run: echo "The calculated sum is 1"
