name: my-expression-action
run-name: my-cool-expression-action

on:
  workflow_dispatch:
    inputs:
      number1:
        description: "number"
        required: true
        default: "1"
        type: string
      number2:
        description: "number"
        required: true
        default: "1"
        type: string
jobs:
  my-expression-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sum two numbers
        id: sum
        run: |
          NUMBER1=${{ inputs.number1 }}
          NUMBER2=${{ inputs.number2 }}
          SUM=$((NUMBER1 + NUMBER2))
          echo "The sum of $NUMBER1 and $NUMBER2 is $SUM"
          echo "::set-output name=sum::$SUM"
      - name: Output the sum
        run: echo "The calculated sum is ${{ steps.sum.outputs.sum }}"
      - name: Determine Result
        id: determine_result
        run: |
          SUM=${{ steps.sum.outputs.sum }}
          if [ "$SUM" -gt 15 ]; then
            echo "::set-output name=result::PASSED"
          else
            echo "::set-output name=result::FAILED"
          fi

      - name: Show Result
        run: echo "${{ steps.determine_result.outputs.result }}"
