name: my-cool-action
on: [push]
jobs:
  run-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: runs Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: crear variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: runs the script
        run: node src/index.js
